# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportShoes', models.IntegerField()),
                ('sportShoesRange', models.IntegerField()),
                ('sneakers', models.IntegerField()),
                ('sneakersRange', models.IntegerField()),
                ('casual', models.IntegerField()),
                ('casualRange', models.IntegerField()),
                ('formal', models.IntegerField()),
                ('formalRange', models.IntegerField()),
                ('sandal', models.IntegerField()),
                ('sandalRange', models.IntegerField()),
                ('boots', models.IntegerField()),
                ('bootsRange', models.IntegerField()),
                ('floaters', models.IntegerField()),
                ('floatersRange', models.IntegerField()),
            ],
        ),
    ]
