# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='bootsRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='casual',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='casualRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='floatersRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='formal',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='formalRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sandalRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sneakersRange',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sportShoes',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sportShoesRange',
        ),
        migrations.AddField(
            model_name='shoes',
            name='boots_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='casual_Shoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='casual_Shoes_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='floaters_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='formal_Shoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='formal_Shoes_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sandal_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sneakers_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sport_Shoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sport_Shoes_Range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='boots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='floaters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='sandal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='sneakers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
