# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polos_and_tees', models.IntegerField(blank=True, null=True)),
                ('polos_and_tees_Range', models.IntegerField(blank=True, null=True)),
                ('casual_Shirts', models.IntegerField(blank=True, null=True)),
                ('casual_Shirts_Range', models.IntegerField(blank=True, null=True)),
                ('formal_Shirts', models.IntegerField(blank=True, null=True)),
                ('formal_Shirts_Range', models.IntegerField(blank=True, null=True)),
                ('sweaters', models.IntegerField(blank=True, null=True)),
                ('sweaters_Range', models.IntegerField(blank=True, null=True)),
                ('cardigans', models.IntegerField(blank=True, null=True)),
                ('cardigans_Range', models.IntegerField(blank=True, null=True)),
                ('jackets', models.IntegerField(blank=True, null=True)),
                ('jackets_Range', models.IntegerField(blank=True, null=True)),
                ('hoodies', models.IntegerField(blank=True, null=True)),
                ('hoodies_Range', models.IntegerField(blank=True, null=True)),
                ('denims', models.IntegerField(blank=True, null=True)),
                ('denims_Range', models.IntegerField(blank=True, null=True)),
                ('trousers', models.IntegerField(blank=True, null=True)),
                ('trousers_Range', models.IntegerField(blank=True, null=True)),
                ('shorts_and_34ths', models.IntegerField(blank=True, null=True)),
                ('shorts_and_34ths_Range', models.IntegerField(blank=True, null=True)),
                ('trackpants', models.IntegerField(blank=True, null=True)),
                ('trackpants_Range', models.IntegerField(blank=True, null=True)),
                ('suits', models.IntegerField(blank=True, null=True)),
                ('suits_Range', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
