# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_watches', models.IntegerField(blank=True, null=True)),
                ('formal_watches_Range', models.IntegerField(blank=True, null=True)),
                ('digital_watches', models.IntegerField(blank=True, null=True)),
                ('digital_watches_Range', models.IntegerField(blank=True, null=True)),
                ('backpacks', models.IntegerField(blank=True, null=True)),
                ('backpacks_Range', models.IntegerField(blank=True, null=True)),
                ('laptop_backpack', models.IntegerField(blank=True, null=True)),
                ('laptop_backpack_Range', models.IntegerField(blank=True, null=True)),
                ('travelbags', models.IntegerField(blank=True, null=True)),
                ('travelbags_Range', models.IntegerField(blank=True, null=True)),
                ('sunglasses', models.IntegerField(blank=True, null=True)),
                ('sunglasses_Range', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
